// <auto-generated />
namespace CsHealthcare.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addDialysistable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDialysistable2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801271736354_add-Dialysis-table-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
