namespace CsHealthcare.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class testreport : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CBCTests", "HaemoglobinUnit", c => c.String());
            AddColumn("dbo.CBCTests", "HematocritUnit", c => c.String());
            AddColumn("dbo.CBCTests", "RedCellsCountUnit", c => c.String());
            AddColumn("dbo.CBCTests", "MeanCellVolumeUnit", c => c.String());
            AddColumn("dbo.CBCTests", "MeanCellHaemoglobinUnit", c => c.String());
            AddColumn("dbo.CBCTests", "MeanCellHaemoglobinConcentrationUnit", c => c.String());
            AddColumn("dbo.CBCTests", "RedCellDistributionWidthUnit", c => c.String());
            AddColumn("dbo.CBCTests", "NucleatedRedBloodCellsUnit", c => c.String());
            AddColumn("dbo.CBCTests", "TotalWbcCountUnit", c => c.String());
            AddColumn("dbo.CBCTests", "NeutrophilUnit", c => c.String());
            AddColumn("dbo.CBCTests", "LymphocyteUnit", c => c.String());
            AddColumn("dbo.CBCTests", "MonocyteUnit", c => c.String());
            AddColumn("dbo.CBCTests", "EosinophilUnit", c => c.String());
            AddColumn("dbo.CBCTests", "BasophilUnit", c => c.String());
            AddColumn("dbo.CBCTests", "ImmatureGranulocytesUnit", c => c.String());
            AddColumn("dbo.CBCTests", "NeutrophilsUnit", c => c.String());
            AddColumn("dbo.CBCTests", "LymphocytesUnit", c => c.String());
            AddColumn("dbo.CBCTests", "MonocytesUnit", c => c.String());
            AddColumn("dbo.CBCTests", "EosinophilsUnit", c => c.String());
            AddColumn("dbo.CBCTests", "BasophilsUnit", c => c.String());
            AddColumn("dbo.CBCTests", "ImmatureGranulocytessUnit", c => c.String());
            AddColumn("dbo.CBCTests", "PlateletsCountUnit", c => c.String());
            AddColumn("dbo.CBCTests", "ErythrocyteSedimentationRateUnit", c => c.String());
            AddColumn("dbo.CBCTests", "HaemoglobinRefer", c => c.String());
            AddColumn("dbo.CBCTests", "HematocritRefer", c => c.String());
            AddColumn("dbo.CBCTests", "RedCellsCountRefer", c => c.String());
            AddColumn("dbo.CBCTests", "MeanCellVolumeRefer", c => c.String());
            AddColumn("dbo.CBCTests", "MeanCellHaemoglobinRefer", c => c.String());
            AddColumn("dbo.CBCTests", "MeanCellHaemoglobinConcentrationRefer", c => c.String());
            AddColumn("dbo.CBCTests", "RedCellDistributionWidthRefer", c => c.String());
            AddColumn("dbo.CBCTests", "NucleatedRedBloodCellsRefer", c => c.String());
            AddColumn("dbo.CBCTests", "TotalWbcCountRefer", c => c.String());
            AddColumn("dbo.CBCTests", "NeutrophilRefer", c => c.String());
            AddColumn("dbo.CBCTests", "LymphocyteRefer", c => c.String());
            AddColumn("dbo.CBCTests", "MonocyteRefer", c => c.String());
            AddColumn("dbo.CBCTests", "EosinophilRefer", c => c.String());
            AddColumn("dbo.CBCTests", "BasophilRefer", c => c.String());
            AddColumn("dbo.CBCTests", "ImmatureGranulocytesRefer", c => c.String());
            AddColumn("dbo.CBCTests", "NeutrophilsRefer", c => c.String());
            AddColumn("dbo.CBCTests", "LymphocytesRefer", c => c.String());
            AddColumn("dbo.CBCTests", "MonocytesRefer", c => c.String());
            AddColumn("dbo.CBCTests", "EosinophilsRefer", c => c.String());
            AddColumn("dbo.CBCTests", "BasophilsRefer", c => c.String());
            AddColumn("dbo.CBCTests", "ImmatureGranulocytessRefer", c => c.String());
            AddColumn("dbo.CBCTests", "PlateletsCountRefer", c => c.String());
            AddColumn("dbo.CBCTests", "ErythrocyteSedimentationRateRefer", c => c.String());
            AddColumn("dbo.CBCTests", "Department", c => c.String(maxLength: 200));
            AddColumn("dbo.RETests", "ColourUnit", c => c.String());
            AddColumn("dbo.RETests", "ClarityUnit", c => c.String());
            AddColumn("dbo.RETests", "TurbidityUnit", c => c.String());
            AddColumn("dbo.RETests", "SedimentUnit", c => c.String());
            AddColumn("dbo.RETests", "AlbuminUnit", c => c.String());
            AddColumn("dbo.RETests", "SpecificgravityUnit", c => c.String());
            AddColumn("dbo.RETests", "PHUnit", c => c.String());
            AddColumn("dbo.RETests", "ProteinUnit", c => c.String());
            AddColumn("dbo.RETests", "GlucoseUnit", c => c.String());
            AddColumn("dbo.RETests", "KetonesUnit", c => c.String());
            AddColumn("dbo.RETests", "BloodUnit", c => c.String());
            AddColumn("dbo.RETests", "BilirubinUnit", c => c.String());
            AddColumn("dbo.RETests", "UrobilinogenUnit", c => c.String());
            AddColumn("dbo.RETests", "NitriteUnit", c => c.String());
            AddColumn("dbo.RETests", "PuscellsUnit", c => c.String());
            AddColumn("dbo.RETests", "EpithelialCellsUnit", c => c.String());
            AddColumn("dbo.RETests", "CrystalsUnit", c => c.String());
            AddColumn("dbo.RETests", "RedBloodCellUnit", c => c.String());
            AddColumn("dbo.RETests", "HyalineCastUnit", c => c.String());
            AddColumn("dbo.RETests", "GranularCastUnit", c => c.String());
            AddColumn("dbo.RETests", "WbcCastUnit", c => c.String());
            AddColumn("dbo.RETests", "RbcCastUnit", c => c.String());
            AddColumn("dbo.RETests", "CalciumOxalateUnit", c => c.String());
            AddColumn("dbo.RETests", "UricAcidUnit", c => c.String());
            AddColumn("dbo.RETests", "TriplePhosphateUnit", c => c.String());
            AddColumn("dbo.RETests", "AmorphosphateUnit", c => c.String());
            AddColumn("dbo.RETests", "YeastCandidaUnit", c => c.String());
            AddColumn("dbo.RETests", "TrichomonasVaginalisUnit", c => c.String());
            AddColumn("dbo.RETests", "SpermatozoaUnit", c => c.String());
            AddColumn("dbo.RETests", "OthersUnit", c => c.String());
            AddColumn("dbo.RETests", "ColourRefer", c => c.String());
            AddColumn("dbo.RETests", "ClarityRefer", c => c.String());
            AddColumn("dbo.RETests", "TurbidityRefer", c => c.String());
            AddColumn("dbo.RETests", "SedimentRefer", c => c.String());
            AddColumn("dbo.RETests", "AlbuminRefer", c => c.String());
            AddColumn("dbo.RETests", "SpecificgravityRefer", c => c.String());
            AddColumn("dbo.RETests", "PHRefer", c => c.String());
            AddColumn("dbo.RETests", "ProteinRefer", c => c.String());
            AddColumn("dbo.RETests", "GlucoseRefer", c => c.String());
            AddColumn("dbo.RETests", "KetonesRefer", c => c.String());
            AddColumn("dbo.RETests", "BloodRefer", c => c.String());
            AddColumn("dbo.RETests", "BilirubinRefer", c => c.String());
            AddColumn("dbo.RETests", "UrobilinogenRefer", c => c.String());
            AddColumn("dbo.RETests", "NitriteRefer", c => c.String());
            AddColumn("dbo.RETests", "PuscellsRefer", c => c.String());
            AddColumn("dbo.RETests", "EpithelialCellsRefer", c => c.String());
            AddColumn("dbo.RETests", "CrystalsRefer", c => c.String());
            AddColumn("dbo.RETests", "RedBloodCellRefer", c => c.String());
            AddColumn("dbo.RETests", "HyalineCastRefer", c => c.String());
            AddColumn("dbo.RETests", "GranularCastRefer", c => c.String());
            AddColumn("dbo.RETests", "WbcCastRefer", c => c.String());
            AddColumn("dbo.RETests", "RbcCastRefer", c => c.String());
            AddColumn("dbo.RETests", "CalciumOxalateRefer", c => c.String());
            AddColumn("dbo.RETests", "UricAcidRefer", c => c.String());
            AddColumn("dbo.RETests", "TriplePhosphateRefer", c => c.String());
            AddColumn("dbo.RETests", "AmorphosphateRefer", c => c.String());
            AddColumn("dbo.RETests", "YeastCandidaRefer", c => c.String());
            AddColumn("dbo.RETests", "TrichomonasVaginalisRefer", c => c.String());
            AddColumn("dbo.RETests", "SpermatozoaRefer", c => c.String());
            AddColumn("dbo.RETests", "OthersRefer", c => c.String());
            AddColumn("dbo.RETests", "Department", c => c.String(maxLength: 200));
            AddColumn("dbo.SRETests", "ColourUnit", c => c.String());
            AddColumn("dbo.SRETests", "ConsistencyUnit", c => c.String());
            AddColumn("dbo.SRETests", "MucusUnit", c => c.String());
            AddColumn("dbo.SRETests", "BloodUnit", c => c.String());
            AddColumn("dbo.SRETests", "ReactionUnit", c => c.String());
            AddColumn("dbo.SRETests", "ReducingSubstanceUnit", c => c.String());
            AddColumn("dbo.SRETests", "OccultBloodTestUnit", c => c.String());
            AddColumn("dbo.SRETests", "PusCellsUnit", c => c.String());
            AddColumn("dbo.SRETests", "RedBloodCellsUnit", c => c.String());
            AddColumn("dbo.SRETests", "MacrophageUnit", c => c.String());
            AddColumn("dbo.SRETests", "VegetableCellsUnit", c => c.String());
            AddColumn("dbo.SRETests", "StarchGranulesUnit", c => c.String());
            AddColumn("dbo.SRETests", "MuscleFibresUnit", c => c.String());
            AddColumn("dbo.SRETests", "FatGlobulesUnit", c => c.String());
            AddColumn("dbo.SRETests", "OvaUnit", c => c.String());
            AddColumn("dbo.SRETests", "ProtozoaUnit", c => c.String());
            AddColumn("dbo.SRETests", "CystsUnit", c => c.String());
            AddColumn("dbo.SRETests", "OthersUnit", c => c.String());
            AddColumn("dbo.SRETests", "ColourRefer", c => c.String());
            AddColumn("dbo.SRETests", "ConsistencyRefer", c => c.String());
            AddColumn("dbo.SRETests", "MucusRefer", c => c.String());
            AddColumn("dbo.SRETests", "BloodRefer", c => c.String());
            AddColumn("dbo.SRETests", "ReactionRefer", c => c.String());
            AddColumn("dbo.SRETests", "ReducingSubstanceRefer", c => c.String());
            AddColumn("dbo.SRETests", "OccultBloodTestRefer", c => c.String());
            AddColumn("dbo.SRETests", "PusCellsRefer", c => c.String());
            AddColumn("dbo.SRETests", "RedBloodCellsRefer", c => c.String());
            AddColumn("dbo.SRETests", "MacrophageRefer", c => c.String());
            AddColumn("dbo.SRETests", "VegetableCellsRefer", c => c.String());
            AddColumn("dbo.SRETests", "StarchGranulesRefer", c => c.String());
            AddColumn("dbo.SRETests", "MuscleFibresRefer", c => c.String());
            AddColumn("dbo.SRETests", "FatGlobulesRefer", c => c.String());
            AddColumn("dbo.SRETests", "OvaRefer", c => c.String());
            AddColumn("dbo.SRETests", "ProtozoaRefer", c => c.String());
            AddColumn("dbo.SRETests", "CystsRefer", c => c.String());
            AddColumn("dbo.SRETests", "OthersRefer", c => c.String());
            AddColumn("dbo.SRETests", "Department", c => c.String(maxLength: 200));
        }
        
        public override void Down()
        {
            DropColumn("dbo.SRETests", "Department");
            DropColumn("dbo.SRETests", "OthersRefer");
            DropColumn("dbo.SRETests", "CystsRefer");
            DropColumn("dbo.SRETests", "ProtozoaRefer");
            DropColumn("dbo.SRETests", "OvaRefer");
            DropColumn("dbo.SRETests", "FatGlobulesRefer");
            DropColumn("dbo.SRETests", "MuscleFibresRefer");
            DropColumn("dbo.SRETests", "StarchGranulesRefer");
            DropColumn("dbo.SRETests", "VegetableCellsRefer");
            DropColumn("dbo.SRETests", "MacrophageRefer");
            DropColumn("dbo.SRETests", "RedBloodCellsRefer");
            DropColumn("dbo.SRETests", "PusCellsRefer");
            DropColumn("dbo.SRETests", "OccultBloodTestRefer");
            DropColumn("dbo.SRETests", "ReducingSubstanceRefer");
            DropColumn("dbo.SRETests", "ReactionRefer");
            DropColumn("dbo.SRETests", "BloodRefer");
            DropColumn("dbo.SRETests", "MucusRefer");
            DropColumn("dbo.SRETests", "ConsistencyRefer");
            DropColumn("dbo.SRETests", "ColourRefer");
            DropColumn("dbo.SRETests", "OthersUnit");
            DropColumn("dbo.SRETests", "CystsUnit");
            DropColumn("dbo.SRETests", "ProtozoaUnit");
            DropColumn("dbo.SRETests", "OvaUnit");
            DropColumn("dbo.SRETests", "FatGlobulesUnit");
            DropColumn("dbo.SRETests", "MuscleFibresUnit");
            DropColumn("dbo.SRETests", "StarchGranulesUnit");
            DropColumn("dbo.SRETests", "VegetableCellsUnit");
            DropColumn("dbo.SRETests", "MacrophageUnit");
            DropColumn("dbo.SRETests", "RedBloodCellsUnit");
            DropColumn("dbo.SRETests", "PusCellsUnit");
            DropColumn("dbo.SRETests", "OccultBloodTestUnit");
            DropColumn("dbo.SRETests", "ReducingSubstanceUnit");
            DropColumn("dbo.SRETests", "ReactionUnit");
            DropColumn("dbo.SRETests", "BloodUnit");
            DropColumn("dbo.SRETests", "MucusUnit");
            DropColumn("dbo.SRETests", "ConsistencyUnit");
            DropColumn("dbo.SRETests", "ColourUnit");
            DropColumn("dbo.RETests", "Department");
            DropColumn("dbo.RETests", "OthersRefer");
            DropColumn("dbo.RETests", "SpermatozoaRefer");
            DropColumn("dbo.RETests", "TrichomonasVaginalisRefer");
            DropColumn("dbo.RETests", "YeastCandidaRefer");
            DropColumn("dbo.RETests", "AmorphosphateRefer");
            DropColumn("dbo.RETests", "TriplePhosphateRefer");
            DropColumn("dbo.RETests", "UricAcidRefer");
            DropColumn("dbo.RETests", "CalciumOxalateRefer");
            DropColumn("dbo.RETests", "RbcCastRefer");
            DropColumn("dbo.RETests", "WbcCastRefer");
            DropColumn("dbo.RETests", "GranularCastRefer");
            DropColumn("dbo.RETests", "HyalineCastRefer");
            DropColumn("dbo.RETests", "RedBloodCellRefer");
            DropColumn("dbo.RETests", "CrystalsRefer");
            DropColumn("dbo.RETests", "EpithelialCellsRefer");
            DropColumn("dbo.RETests", "PuscellsRefer");
            DropColumn("dbo.RETests", "NitriteRefer");
            DropColumn("dbo.RETests", "UrobilinogenRefer");
            DropColumn("dbo.RETests", "BilirubinRefer");
            DropColumn("dbo.RETests", "BloodRefer");
            DropColumn("dbo.RETests", "KetonesRefer");
            DropColumn("dbo.RETests", "GlucoseRefer");
            DropColumn("dbo.RETests", "ProteinRefer");
            DropColumn("dbo.RETests", "PHRefer");
            DropColumn("dbo.RETests", "SpecificgravityRefer");
            DropColumn("dbo.RETests", "AlbuminRefer");
            DropColumn("dbo.RETests", "SedimentRefer");
            DropColumn("dbo.RETests", "TurbidityRefer");
            DropColumn("dbo.RETests", "ClarityRefer");
            DropColumn("dbo.RETests", "ColourRefer");
            DropColumn("dbo.RETests", "OthersUnit");
            DropColumn("dbo.RETests", "SpermatozoaUnit");
            DropColumn("dbo.RETests", "TrichomonasVaginalisUnit");
            DropColumn("dbo.RETests", "YeastCandidaUnit");
            DropColumn("dbo.RETests", "AmorphosphateUnit");
            DropColumn("dbo.RETests", "TriplePhosphateUnit");
            DropColumn("dbo.RETests", "UricAcidUnit");
            DropColumn("dbo.RETests", "CalciumOxalateUnit");
            DropColumn("dbo.RETests", "RbcCastUnit");
            DropColumn("dbo.RETests", "WbcCastUnit");
            DropColumn("dbo.RETests", "GranularCastUnit");
            DropColumn("dbo.RETests", "HyalineCastUnit");
            DropColumn("dbo.RETests", "RedBloodCellUnit");
            DropColumn("dbo.RETests", "CrystalsUnit");
            DropColumn("dbo.RETests", "EpithelialCellsUnit");
            DropColumn("dbo.RETests", "PuscellsUnit");
            DropColumn("dbo.RETests", "NitriteUnit");
            DropColumn("dbo.RETests", "UrobilinogenUnit");
            DropColumn("dbo.RETests", "BilirubinUnit");
            DropColumn("dbo.RETests", "BloodUnit");
            DropColumn("dbo.RETests", "KetonesUnit");
            DropColumn("dbo.RETests", "GlucoseUnit");
            DropColumn("dbo.RETests", "ProteinUnit");
            DropColumn("dbo.RETests", "PHUnit");
            DropColumn("dbo.RETests", "SpecificgravityUnit");
            DropColumn("dbo.RETests", "AlbuminUnit");
            DropColumn("dbo.RETests", "SedimentUnit");
            DropColumn("dbo.RETests", "TurbidityUnit");
            DropColumn("dbo.RETests", "ClarityUnit");
            DropColumn("dbo.RETests", "ColourUnit");
            DropColumn("dbo.CBCTests", "Department");
            DropColumn("dbo.CBCTests", "ErythrocyteSedimentationRateRefer");
            DropColumn("dbo.CBCTests", "PlateletsCountRefer");
            DropColumn("dbo.CBCTests", "ImmatureGranulocytessRefer");
            DropColumn("dbo.CBCTests", "BasophilsRefer");
            DropColumn("dbo.CBCTests", "EosinophilsRefer");
            DropColumn("dbo.CBCTests", "MonocytesRefer");
            DropColumn("dbo.CBCTests", "LymphocytesRefer");
            DropColumn("dbo.CBCTests", "NeutrophilsRefer");
            DropColumn("dbo.CBCTests", "ImmatureGranulocytesRefer");
            DropColumn("dbo.CBCTests", "BasophilRefer");
            DropColumn("dbo.CBCTests", "EosinophilRefer");
            DropColumn("dbo.CBCTests", "MonocyteRefer");
            DropColumn("dbo.CBCTests", "LymphocyteRefer");
            DropColumn("dbo.CBCTests", "NeutrophilRefer");
            DropColumn("dbo.CBCTests", "TotalWbcCountRefer");
            DropColumn("dbo.CBCTests", "NucleatedRedBloodCellsRefer");
            DropColumn("dbo.CBCTests", "RedCellDistributionWidthRefer");
            DropColumn("dbo.CBCTests", "MeanCellHaemoglobinConcentrationRefer");
            DropColumn("dbo.CBCTests", "MeanCellHaemoglobinRefer");
            DropColumn("dbo.CBCTests", "MeanCellVolumeRefer");
            DropColumn("dbo.CBCTests", "RedCellsCountRefer");
            DropColumn("dbo.CBCTests", "HematocritRefer");
            DropColumn("dbo.CBCTests", "HaemoglobinRefer");
            DropColumn("dbo.CBCTests", "ErythrocyteSedimentationRateUnit");
            DropColumn("dbo.CBCTests", "PlateletsCountUnit");
            DropColumn("dbo.CBCTests", "ImmatureGranulocytessUnit");
            DropColumn("dbo.CBCTests", "BasophilsUnit");
            DropColumn("dbo.CBCTests", "EosinophilsUnit");
            DropColumn("dbo.CBCTests", "MonocytesUnit");
            DropColumn("dbo.CBCTests", "LymphocytesUnit");
            DropColumn("dbo.CBCTests", "NeutrophilsUnit");
            DropColumn("dbo.CBCTests", "ImmatureGranulocytesUnit");
            DropColumn("dbo.CBCTests", "BasophilUnit");
            DropColumn("dbo.CBCTests", "EosinophilUnit");
            DropColumn("dbo.CBCTests", "MonocyteUnit");
            DropColumn("dbo.CBCTests", "LymphocyteUnit");
            DropColumn("dbo.CBCTests", "NeutrophilUnit");
            DropColumn("dbo.CBCTests", "TotalWbcCountUnit");
            DropColumn("dbo.CBCTests", "NucleatedRedBloodCellsUnit");
            DropColumn("dbo.CBCTests", "RedCellDistributionWidthUnit");
            DropColumn("dbo.CBCTests", "MeanCellHaemoglobinConcentrationUnit");
            DropColumn("dbo.CBCTests", "MeanCellHaemoglobinUnit");
            DropColumn("dbo.CBCTests", "MeanCellVolumeUnit");
            DropColumn("dbo.CBCTests", "RedCellsCountUnit");
            DropColumn("dbo.CBCTests", "HematocritUnit");
            DropColumn("dbo.CBCTests", "HaemoglobinUnit");
        }
    }
}
