namespace CsHealthcare.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class conflictmigration234 : DbMigration
    {
        public override void Up()
        {
            //AddColumn("dbo.BioChemistries", "SBilirubin", c => c.String());
            //AddColumn("dbo.BioChemistries", "BloodGlucoseRandomUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "BloodGlucoseFastingUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "Twohrsafter75gmGlucoseUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "BloodGlucoseTwohrsABFUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SBilirubinUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "UreaUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SCreatinineUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SUricAcidUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SASTUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SALTUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SAlkalinePhosphataseUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SAlkalinePhosphataseProteinUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SCalciumUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SIronUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "STIBCUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SInorganicPhosphateUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SMagnesiumUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SodiumUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "PotassiumUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "ChlorideUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "TotalCarbondioxaidUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SCholesterolUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "STriglyceridesUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "SHDLCholesterolUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "TroponinIUnit", c => c.String());
            //AddColumn("dbo.BioChemistries", "BloodGlucoseRandomRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "BloodGlucoseFastingRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "Twohrsafter75gmGlucoseRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "BloodGlucoseTwohrsABFRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "UreaRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SBilirubinRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SCreatinineRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SUricAcidRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SASTRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SALTRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SAlkalinePhosphataseRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SAlkalinePhosphataseProteinRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SCalciumRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SIronRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "STIBCRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SInorganicPhosphateRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SMagnesiumRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SodiumRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "PotassiumRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "ChlorideRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "TotalCarbondioxaidRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SCholesterolRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "STriglyceridesRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "SHDLCholesterolRef", c => c.String());
            //AddColumn("dbo.BioChemistries", "TroponinIRef", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "T3Unit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "T4Unit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "TSHUnit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "FreeT3Unit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "FreeT4Unit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "FSHUnit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "LHUnit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "ProlactinUnit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "STestosteroneUnit", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "T3Ref", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "T4Ref", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "TSHRef", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "FreeT3Ref", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "FreeT4Ref", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "FSHRef", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "LHRef", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "ProlactinRef", c => c.String());
            //AddColumn("dbo.ENDOCRINOLOGies", "STestosteroneRef", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "βhCGUnit", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "PSAUnit", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "SFerritinUnit", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "TIgEUnit", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "βhCGRef", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "PSARef", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "SFerritinRef", c => c.String());
            //AddColumn("dbo.IMMUNOLOGICALs", "TIgERef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "CRPUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "RAUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "ASOUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "HBsAgUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "BloodGroupUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "RhFactorUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "UrineforPregnancyTestUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "VDRLUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "TOUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "THUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "AHUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "BHUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "AOUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "BOUnit", c => c.String());
            //AddColumn("dbo.SEROLOGies", "CRPRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "RARef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "ASORef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "HBsAgRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "BloodGroupRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "RhFactorRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "UrineforPregnancyTestRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "VDRLRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "TORef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "THRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "AHRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "BHRef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "AORef", c => c.String());
            //AddColumn("dbo.SEROLOGies", "BORef", c => c.String());
        }
        
        public override void Down()
        {
            //DropColumn("dbo.SEROLOGies", "BORef");
            //DropColumn("dbo.SEROLOGies", "AORef");
            //DropColumn("dbo.SEROLOGies", "BHRef");
            //DropColumn("dbo.SEROLOGies", "AHRef");
            //DropColumn("dbo.SEROLOGies", "THRef");
            //DropColumn("dbo.SEROLOGies", "TORef");
            //DropColumn("dbo.SEROLOGies", "VDRLRef");
            //DropColumn("dbo.SEROLOGies", "UrineforPregnancyTestRef");
            //DropColumn("dbo.SEROLOGies", "RhFactorRef");
            //DropColumn("dbo.SEROLOGies", "BloodGroupRef");
            //DropColumn("dbo.SEROLOGies", "HBsAgRef");
            //DropColumn("dbo.SEROLOGies", "ASORef");
            //DropColumn("dbo.SEROLOGies", "RARef");
            //DropColumn("dbo.SEROLOGies", "CRPRef");
            //DropColumn("dbo.SEROLOGies", "BOUnit");
            //DropColumn("dbo.SEROLOGies", "AOUnit");
            //DropColumn("dbo.SEROLOGies", "BHUnit");
            //DropColumn("dbo.SEROLOGies", "AHUnit");
            //DropColumn("dbo.SEROLOGies", "THUnit");
            //DropColumn("dbo.SEROLOGies", "TOUnit");
            //DropColumn("dbo.SEROLOGies", "VDRLUnit");
            //DropColumn("dbo.SEROLOGies", "UrineforPregnancyTestUnit");
            //DropColumn("dbo.SEROLOGies", "RhFactorUnit");
            //DropColumn("dbo.SEROLOGies", "BloodGroupUnit");
            //DropColumn("dbo.SEROLOGies", "HBsAgUnit");
            //DropColumn("dbo.SEROLOGies", "ASOUnit");
            //DropColumn("dbo.SEROLOGies", "RAUnit");
            //DropColumn("dbo.SEROLOGies", "CRPUnit");
            //DropColumn("dbo.IMMUNOLOGICALs", "TIgERef");
            //DropColumn("dbo.IMMUNOLOGICALs", "SFerritinRef");
            //DropColumn("dbo.IMMUNOLOGICALs", "PSARef");
            //DropColumn("dbo.IMMUNOLOGICALs", "βhCGRef");
            //DropColumn("dbo.IMMUNOLOGICALs", "TIgEUnit");
            //DropColumn("dbo.IMMUNOLOGICALs", "SFerritinUnit");
            //DropColumn("dbo.IMMUNOLOGICALs", "PSAUnit");
            //DropColumn("dbo.IMMUNOLOGICALs", "βhCGUnit");
            //DropColumn("dbo.ENDOCRINOLOGies", "STestosteroneRef");
            //DropColumn("dbo.ENDOCRINOLOGies", "ProlactinRef");
            //DropColumn("dbo.ENDOCRINOLOGies", "LHRef");
            //DropColumn("dbo.ENDOCRINOLOGies", "FSHRef");
            //DropColumn("dbo.ENDOCRINOLOGies", "FreeT4Ref");
            //DropColumn("dbo.ENDOCRINOLOGies", "FreeT3Ref");
            //DropColumn("dbo.ENDOCRINOLOGies", "TSHRef");
            //DropColumn("dbo.ENDOCRINOLOGies", "T4Ref");
            //DropColumn("dbo.ENDOCRINOLOGies", "T3Ref");
            //DropColumn("dbo.ENDOCRINOLOGies", "STestosteroneUnit");
            //DropColumn("dbo.ENDOCRINOLOGies", "ProlactinUnit");
            //DropColumn("dbo.ENDOCRINOLOGies", "LHUnit");
            //DropColumn("dbo.ENDOCRINOLOGies", "FSHUnit");
            //DropColumn("dbo.ENDOCRINOLOGies", "FreeT4Unit");
            //DropColumn("dbo.ENDOCRINOLOGies", "FreeT3Unit");
            //DropColumn("dbo.ENDOCRINOLOGies", "TSHUnit");
            //DropColumn("dbo.ENDOCRINOLOGies", "T4Unit");
            //DropColumn("dbo.ENDOCRINOLOGies", "T3Unit");
            //DropColumn("dbo.BioChemistries", "TroponinIRef");
            //DropColumn("dbo.BioChemistries", "SHDLCholesterolRef");
            //DropColumn("dbo.BioChemistries", "STriglyceridesRef");
            //DropColumn("dbo.BioChemistries", "SCholesterolRef");
            //DropColumn("dbo.BioChemistries", "TotalCarbondioxaidRef");
            //DropColumn("dbo.BioChemistries", "ChlorideRef");
            //DropColumn("dbo.BioChemistries", "PotassiumRef");
            //DropColumn("dbo.BioChemistries", "SodiumRef");
            //DropColumn("dbo.BioChemistries", "SMagnesiumRef");
            //DropColumn("dbo.BioChemistries", "SInorganicPhosphateRef");
            //DropColumn("dbo.BioChemistries", "STIBCRef");
            //DropColumn("dbo.BioChemistries", "SIronRef");
            //DropColumn("dbo.BioChemistries", "SCalciumRef");
            //DropColumn("dbo.BioChemistries", "SAlkalinePhosphataseProteinRef");
            //DropColumn("dbo.BioChemistries", "SAlkalinePhosphataseRef");
            //DropColumn("dbo.BioChemistries", "SALTRef");
            //DropColumn("dbo.BioChemistries", "SASTRef");
            //DropColumn("dbo.BioChemistries", "SUricAcidRef");
            //DropColumn("dbo.BioChemistries", "SCreatinineRef");
            //DropColumn("dbo.BioChemistries", "SBilirubinRef");
            //DropColumn("dbo.BioChemistries", "UreaRef");
            //DropColumn("dbo.BioChemistries", "BloodGlucoseTwohrsABFRef");
            //DropColumn("dbo.BioChemistries", "Twohrsafter75gmGlucoseRef");
            //DropColumn("dbo.BioChemistries", "BloodGlucoseFastingRef");
            //DropColumn("dbo.BioChemistries", "BloodGlucoseRandomRef");
            //DropColumn("dbo.BioChemistries", "TroponinIUnit");
            //DropColumn("dbo.BioChemistries", "SHDLCholesterolUnit");
            //DropColumn("dbo.BioChemistries", "STriglyceridesUnit");
            //DropColumn("dbo.BioChemistries", "SCholesterolUnit");
            //DropColumn("dbo.BioChemistries", "TotalCarbondioxaidUnit");
            //DropColumn("dbo.BioChemistries", "ChlorideUnit");
            //DropColumn("dbo.BioChemistries", "PotassiumUnit");
            //DropColumn("dbo.BioChemistries", "SodiumUnit");
            //DropColumn("dbo.BioChemistries", "SMagnesiumUnit");
            //DropColumn("dbo.BioChemistries", "SInorganicPhosphateUnit");
            //DropColumn("dbo.BioChemistries", "STIBCUnit");
            //DropColumn("dbo.BioChemistries", "SIronUnit");
            //DropColumn("dbo.BioChemistries", "SCalciumUnit");
            //DropColumn("dbo.BioChemistries", "SAlkalinePhosphataseProteinUnit");
            //DropColumn("dbo.BioChemistries", "SAlkalinePhosphataseUnit");
            //DropColumn("dbo.BioChemistries", "SALTUnit");
            //DropColumn("dbo.BioChemistries", "SASTUnit");
            //DropColumn("dbo.BioChemistries", "SUricAcidUnit");
            //DropColumn("dbo.BioChemistries", "SCreatinineUnit");
            //DropColumn("dbo.BioChemistries", "UreaUnit");
            //DropColumn("dbo.BioChemistries", "SBilirubinUnit");
            //DropColumn("dbo.BioChemistries", "BloodGlucoseTwohrsABFUnit");
            //DropColumn("dbo.BioChemistries", "Twohrsafter75gmGlucoseUnit");
            //DropColumn("dbo.BioChemistries", "BloodGlucoseFastingUnit");
            //DropColumn("dbo.BioChemistries", "BloodGlucoseRandomUnit");
            //DropColumn("dbo.BioChemistries", "SBilirubin");
        }
    }
}
